"""
serialize.py
============
Model artifact serialization and deserialization for CrediShield AI.

Saves trained models as a pair of files:
  <name>.joblib       — Full Python object (preprocessor + model + metadata)
  <name>_meta.json    — Human-readable sidecar: version, metrics, timestamps
                         (no model weights — kept lightweight for logging / auditing)

Usage example
-------------
    from src.serialize import ModelArtifact, save_artifact, load_artifact, get_model_version

    artifact = ModelArtifact(
        preprocessor=preprocessor,
        model=model,
        feature_names=feature_names,
        categorical_features=cat_cols,
        numerical_features=num_cols,
        model_version=get_model_version(),
        trained_at=datetime.utcnow().isoformat(),
        training_metrics={"roc_auc": 0.78, "pr_auc": 0.42},
        threshold_policy={"low_threshold": 0.3, "high_threshold": 0.7},
    )
    save_artifact(artifact, output_dir="models/", name="credishield_v1")
    loaded = load_artifact("models/credishield_v1.joblib")
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import joblib


# ---------------------------------------------------------------------------
# ModelArtifact dataclass
# ---------------------------------------------------------------------------

@dataclass
class ModelArtifact:
    """
    Container for all objects and metadata required to reproduce a prediction.

    Fields
    ------
    preprocessor : ColumnTransformer
        Fitted sklearn ColumnTransformer (OHE + StandardScaler).
    model : XGBClassifier
        Fitted XGBoost binary classifier.
    feature_names : list of str
        Output feature names from the preprocessor (after OHE expansion).
    categorical_features : list of str
        Raw categorical columns fed into the preprocessor.
    numerical_features : list of str
        Raw numerical columns fed into the preprocessor.
    model_version : str
        Version string, e.g. 'v20240101_120000'. Generated by get_model_version().
    trained_at : str
        ISO-8601 UTC timestamp when training was completed.
    training_metrics : dict
        Evaluation metrics from the training run (roc_auc, pr_auc, f1, …).
    threshold_policy : dict
        Decision threshold configuration with keys 'low_threshold',
        'high_threshold', and optionally 'cost_fn_ratio'.
    """

    preprocessor: Any                              # sklearn ColumnTransformer
    model: Any                                     # XGBClassifier
    feature_names: List[str]
    categorical_features: List[str]
    numerical_features: List[str]
    model_version: str
    trained_at: str
    training_metrics: Dict[str, Any] = field(default_factory=dict)
    threshold_policy: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_model_version() -> str:
    """
    Generate a timestamp-based model version string.

    Format: 'v{YYYYMMDD}_{HHMMSS}'

    Returns
    -------
    str
        E.g. 'v20240101_120000'
    """
    now = datetime.now(tz=timezone.utc)
    return now.strftime("v%Y%m%d_%H%M%S")


def save_artifact(
    artifact: ModelArtifact,
    output_dir: str,
    name: str,
) -> Dict[str, str]:
    """
    Persist a ModelArtifact to disk as two files:
      - ``<output_dir>/<name>.joblib``     — Full serialised object (joblib)
      - ``<output_dir>/<name>_meta.json``  — Lightweight metadata sidecar (JSON)

    The JSON sidecar intentionally omits model weights; it is intended for
    logging, auditing, and quick inspection without loading the full artifact.

    Parameters
    ----------
    artifact : ModelArtifact
        The artifact to persist.
    output_dir : str
        Directory to write files into (created if it doesn't exist).
    name : str
        Base filename (without extension).

    Returns
    -------
    dict
        Keys 'joblib_path' and 'meta_path' with resolved absolute paths.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    joblib_path = output_path / f"{name}.joblib"
    meta_path = output_path / f"{name}_meta.json"

    # --- Serialise full artifact ---
    joblib.dump(artifact, joblib_path, compress=3)
    print(f"[save_artifact] Saved joblib -> {joblib_path.resolve()}")

    # --- Build metadata sidecar (no weights) ---
    meta: Dict[str, Any] = {
        "model_version": artifact.model_version,
        "trained_at": artifact.trained_at,
        "training_metrics": artifact.training_metrics,
        "threshold_policy": artifact.threshold_policy,
        "categorical_features": artifact.categorical_features,
        "numerical_features": artifact.numerical_features,
        "feature_names_count": len(artifact.feature_names),
        "joblib_file": joblib_path.name,
    }

    with meta_path.open("w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2)
    print(f"[save_artifact] Saved meta  -> {meta_path.resolve()}")

    return {
        "joblib_path": str(joblib_path.resolve()),
        "meta_path": str(meta_path.resolve()),
    }


def load_artifact(joblib_path: str) -> ModelArtifact:
    """
    Load a ModelArtifact from a .joblib file.

    Parameters
    ----------
    joblib_path : str
        Path to the .joblib file previously saved by save_artifact().

    Returns
    -------
    ModelArtifact
        The fully reconstructed artifact (preprocessor, model, metadata).

    Raises
    ------
    FileNotFoundError
        If the joblib file does not exist.
    TypeError
        If the loaded object is not a ModelArtifact instance.
    """
    path = Path(joblib_path)
    if not path.exists():
        raise FileNotFoundError(f"Artifact not found: {path.resolve()}")

    artifact = joblib.load(path)

    if not isinstance(artifact, ModelArtifact):
        raise TypeError(
            f"Expected ModelArtifact, got {type(artifact).__name__} "
            f"from {path.resolve()}"
        )

    print(
        f"[load_artifact] Loaded '{artifact.model_version}' "
        f"(trained {artifact.trained_at}) from {path.resolve()}"
    )
    return artifact
